title = "EPIC Default Config"

[global]
root = "data/"

[logs]
level = "info"
use_file_logger = false
path = "logs/"
filename = "Debug.log"

[address]
path = ""
filename = "address.toml"
interval = 900

[network]
ip = "0.0.0.0"
port = 7878
type = "Testnet"

[[dns_seeds]]
hostname = "pascal.ieda.ust.hk"
port = 7877

[[ip_seeds]]
ip = "143.89.21.231"
port = 7877

[db]
path = "db/"

[rpc]
port = 3777

[wallet]
path = "wallet/"
backup_period = 600
